language: rust
sudo: false

after_success:
  - curl https://bodoni.github.io/travis/after_success.sh | bash

env:
  global:
    secure: C6iW1+kSPrqW2ZktjrcspHOSAw/mvKO81kk73tDPdOaXqFgSNwnTRM2zFOk2pmtUwu6qTT1RAGPYd2ENNfTP9dfk29mikza7k1mWBkzclJQCVhPhDlrtChlWrCEH7yENAJrBZQtwk3NEN4t+7xcWoU9z+LlfPdSZrfqmrtOPaAY=

notifications:
  email: false
