language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      curl https://bodoni.github.io/travis/update_documentation.sh | bash;
    fi

env:
  global:
    - secure: D6AFvmP6XiVZ9X4zoQatxvzgsVN9iaN5WR9rBvxqarEXuieJQJrgZGc2XTbpwqBOUEut//4Ynj/KxJKmNYQyRwbLqJppmnT+JNqbHXRMyCcO5PU9iyh8AdNNOeHpj/NkuQ4PNZL7lJIZkpi9DFMAxmBBhJ8TTosiWRZi0btYo8o=

notifications:
  email: false
