[package]
name = "svg"
version = "0.1.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/bodoni/svg"
homepage = "https://github.com/bodoni/svg"
documentation = "https://bodoni.github.io/svg"
description = "The package provides an SVG parser."
